// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaFuY34MZzQUxFP6rv0RF-DHGxP6HkwvQ',
    appId: '1:555144730554:web:09272aacbfdb23963aef83',
    messagingSenderId: '555144730554',
    projectId: 'historywalk-dbae6',
    authDomain: 'historywalk-dbae6.firebaseapp.com',
    storageBucket: 'historywalk-dbae6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD612gmz4Fbw_o3UtZGdQHCQSPr_CFoHW0',
    appId: '1:555144730554:android:68dc12e866f3ca8c3aef83',
    messagingSenderId: '555144730554',
    projectId: 'historywalk-dbae6',
    storageBucket: 'historywalk-dbae6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpSICWhJQC8f59M1ROplscF4Oi2YNPV7s',
    appId: '1:555144730554:ios:65ad7867949263763aef83',
    messagingSenderId: '555144730554',
    projectId: 'historywalk-dbae6',
    storageBucket: 'historywalk-dbae6.firebasestorage.app',
    iosBundleId: 'com.example.testingFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpSICWhJQC8f59M1ROplscF4Oi2YNPV7s',
    appId: '1:555144730554:ios:65ad7867949263763aef83',
    messagingSenderId: '555144730554',
    projectId: 'historywalk-dbae6',
    storageBucket: 'historywalk-dbae6.firebasestorage.app',
    iosBundleId: 'com.example.testingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaFuY34MZzQUxFP6rv0RF-DHGxP6HkwvQ',
    appId: '1:555144730554:web:ba35564c8ea99e913aef83',
    messagingSenderId: '555144730554',
    projectId: 'historywalk-dbae6',
    authDomain: 'historywalk-dbae6.firebaseapp.com',
    storageBucket: 'historywalk-dbae6.firebasestorage.app',
  );
}
